# pocaflow.pyi

import numpy as np
from typing import Any

def matmul(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...
def matmul_f64(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...
def matmul_f32_cpu(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...

def batch_matmul_f32(batch_a: np.ndarray, batch_b: np.ndarray) -> np.ndarray: ...
def batch_matmul_f64(batch_a: np.ndarray, batch_b: np.ndarray) -> np.ndarray: ...

def strassen_matmul(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...
def strassen_matmul_f32(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...
def strassen_matmul_f64(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...

def dot(a: np.ndarray, b: np.ndarray) -> float: ...
def cross(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...
def magnitude(a: np.ndarray) -> float: ...
def normalize(a: np.ndarray) -> np.ndarray: ...
